sudo: required
services:
  - docker

before_install:
  - docker build -t krismwas/docker-react -f Dockerfile.dev .

script:
#  -- --coverage this is to exit after running test as travis ci expects this
  - docker run krismwas/docker-react npm run test -- --coverage